# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calibrate_Rqv_cluster_probabilities <- function(pi_Ztildeqv_eq_h, E_tr_BiBit_qv, E_log_det_Rqv_inv, E_Rqv_inv, E_Rqv_log_nu_h, E_Rqv_log_1_minus_nu_h, E_sigma_sq_inv, V, N) {
    invisible(.Call('_BBSS_calibrate_Rqv_cluster_probabilities', PACKAGE = 'BBSS', pi_Ztildeqv_eq_h, E_tr_BiBit_qv, E_log_det_Rqv_inv, E_Rqv_inv, E_Rqv_log_nu_h, E_Rqv_log_1_minus_nu_h, E_sigma_sq_inv, V, N))
}

calibrate_Rqv_cluster_parameters <- function(VarHyper_Rqv_df, VarHyper_Rqv_scale, pi_Ztildeqv_eq_h, E_tr_BiBit_qv, base_measure_scale, E_sigma_sq_inv, base_measure_df, V, N) {
    invisible(.Call('_BBSS_calibrate_Rqv_cluster_parameters', PACKAGE = 'BBSS', VarHyper_Rqv_df, VarHyper_Rqv_scale, pi_Ztildeqv_eq_h, E_tr_BiBit_qv, base_measure_scale, E_sigma_sq_inv, base_measure_df, V, N))
}

calibrate_spatial_map_cluster_probabilities <- function(pi_Zqv_eq_h, E_log_nu_h, E_log_1_minus_nu_h, E_log_gamma_h_sq, E_gamma_h_sq_inv, E_mu_h, E_mu_h_sq, E_S, E_S_sq, E_sigma_sq_inv) {
    invisible(.Call('_BBSS_calibrate_spatial_map_cluster_probabilities', PACKAGE = 'BBSS', pi_Zqv_eq_h, E_log_nu_h, E_log_1_minus_nu_h, E_log_gamma_h_sq, E_gamma_h_sq_inv, E_mu_h, E_mu_h_sq, E_S, E_S_sq, E_sigma_sq_inv))
}

calibrate_spatial_map_cluster_parameters <- function(VarHyper_M_h, VarHyper_L_h, VarHyper_A_h, VarHyper_B_h, pi_Zqv_eq_h, E_S, E_S_sq, E_sigma_sq_inv, base_measure_lambda, base_measure_mu, base_measure_alpha, base_measure_beta) {
    invisible(.Call('_BBSS_calibrate_spatial_map_cluster_parameters', PACKAGE = 'BBSS', VarHyper_M_h, VarHyper_L_h, VarHyper_A_h, VarHyper_B_h, pi_Zqv_eq_h, E_S, E_S_sq, E_sigma_sq_inv, base_measure_lambda, base_measure_mu, base_measure_alpha, base_measure_beta))
}

cross_sectional_spatial_map_updates <- function(E_S, E_S_sq, E_Si, Y, pi_Zqv_eq_h, E_gamma_h_sq_inv, E_mu_h, E_sigma_sq_inv) {
    invisible(.Call('_BBSS_cross_sectional_spatial_map_updates', PACKAGE = 'BBSS', E_S, E_S_sq, E_Si, Y, pi_Zqv_eq_h, E_gamma_h_sq_inv, E_mu_h, E_sigma_sq_inv))
}

cross_sectional_siteadj_spatial_map_updates <- function(E_S, E_S_sq, E_b_site, sum_E_b_site_sq, E_Si, trace_E_Si_sq, Y, site_indicators, pi_Zqv_eq_h, E_gamma_h_sq_inv, E_mu_h, E_sigma_sq_inv, E_sigma_site_sq_inv) {
    invisible(.Call('_BBSS_cross_sectional_siteadj_spatial_map_updates', PACKAGE = 'BBSS', E_S, E_S_sq, E_b_site, sum_E_b_site_sq, E_Si, trace_E_Si_sq, Y, site_indicators, pi_Zqv_eq_h, E_gamma_h_sq_inv, E_mu_h, E_sigma_sq_inv, E_sigma_site_sq_inv))
}

cross_sectional_covadj_spatial_map_updates <- function(E_S, E_S_sq, E_Beta, E_Beta_sq, E_Si, trace_E_Si_sq, Y, X, pi_Zqv_eq_h, E_gamma_h_sq_inv, E_mu_h, E_lambda_sq, E_sigma_sq_inv, E_tau_sq_inv) {
    invisible(.Call('_BBSS_cross_sectional_covadj_spatial_map_updates', PACKAGE = 'BBSS', E_S, E_S_sq, E_Beta, E_Beta_sq, E_Si, trace_E_Si_sq, Y, X, pi_Zqv_eq_h, E_gamma_h_sq_inv, E_mu_h, E_lambda_sq, E_sigma_sq_inv, E_tau_sq_inv))
}

cross_sectional_covadj_siteadj_spatial_map_updates <- function(E_S, E_S_sq, E_Beta, E_Beta_sq, E_b_site, sum_E_b_site_sq, E_Si, trace_E_Si_sq, Y, X, site_indicators, pi_Zqv_eq_h, E_gamma_h_sq_inv, E_mu_h, E_lambda_sq, E_sigma_sq_inv, E_tau_sq_inv, E_sigma_site_sq_inv) {
    invisible(.Call('_BBSS_cross_sectional_covadj_siteadj_spatial_map_updates', PACKAGE = 'BBSS', E_S, E_S_sq, E_Beta, E_Beta_sq, E_b_site, sum_E_b_site_sq, E_Si, trace_E_Si_sq, Y, X, site_indicators, pi_Zqv_eq_h, E_gamma_h_sq_inv, E_mu_h, E_lambda_sq, E_sigma_sq_inv, E_tau_sq_inv, E_sigma_site_sq_inv))
}

cross_sectional_covadj_siteadj_spatial_map_blocked_updates <- function(E_S, E_S_sq, E_Beta, E_Beta_sq, E_b_site, sum_E_b_site_sq, E_Si, trace_E_Si_sq, Y, X, site_indicators, pi_Zqv_eq_h, E_gamma_h_sq_inv, E_mu_h, E_lambda_sq, E_sigma_sq_inv, E_tau_sq_inv, E_sigma_site_sq_inv) {
    invisible(.Call('_BBSS_cross_sectional_covadj_siteadj_spatial_map_blocked_updates', PACKAGE = 'BBSS', E_S, E_S_sq, E_Beta, E_Beta_sq, E_b_site, sum_E_b_site_sq, E_Si, trace_E_Si_sq, Y, X, site_indicators, pi_Zqv_eq_h, E_gamma_h_sq_inv, E_mu_h, E_lambda_sq, E_sigma_sq_inv, E_tau_sq_inv, E_sigma_site_sq_inv))
}

update_error_variance_variational_scale <- function(Y_unmixed, pi_Zqv_eq_h, E_S, E_Si, E_S_sq, E_mu_h, E_mu_h_sq, E_gamma_h_sq_inv, sum_trace_YYt, sum_trace_E_Si_sq) {
    .Call('_BBSS_update_error_variance_variational_scale', PACKAGE = 'BBSS', Y_unmixed, pi_Zqv_eq_h, E_S, E_Si, E_S_sq, E_mu_h, E_mu_h_sq, E_gamma_h_sq_inv, sum_trace_YYt, sum_trace_E_Si_sq)
}

update_error_variance_variational_scale_covadj <- function(Y_unmixed, pi_Zqv_eq_h, E_S, E_Si, E_S_sq, E_mu_h, E_mu_h_sq, E_gamma_h_sq_inv, E_Beta_sq, E_lambda_sq, sum_trace_YYt, sum_trace_E_Si_sq, E_tau_sq_inv) {
    .Call('_BBSS_update_error_variance_variational_scale_covadj', PACKAGE = 'BBSS', Y_unmixed, pi_Zqv_eq_h, E_S, E_Si, E_S_sq, E_mu_h, E_mu_h_sq, E_gamma_h_sq_inv, E_Beta_sq, E_lambda_sq, sum_trace_YYt, sum_trace_E_Si_sq, E_tau_sq_inv)
}

eval_LC_cross_sectional_covadj <- function(contrasts, contrast_specification, Y, X, pi_Zqv_eq_h, E_gamma_h_sq_inv, E_mu_h, E_lambda_sq, E_sigma_sq_inv, E_tau_sq_inv, V, calculate_credible_interval, credible_interval_width_pct, calculate_savage_dickey, imp_sample_savage_dickey, n_importance_resample) {
    .Call('_BBSS_eval_LC_cross_sectional_covadj', PACKAGE = 'BBSS', contrasts, contrast_specification, Y, X, pi_Zqv_eq_h, E_gamma_h_sq_inv, E_mu_h, E_lambda_sq, E_sigma_sq_inv, E_tau_sq_inv, V, calculate_credible_interval, credible_interval_width_pct, calculate_savage_dickey, imp_sample_savage_dickey, n_importance_resample)
}

eval_LC_cross_sectional_covadj_siteadj <- function(contrasts, contrast_specification, Y, X, site_indicators, pi_Zqv_eq_h, E_gamma_h_sq_inv, E_mu_h, E_lambda_sq, E_sigma_sq_inv, E_tau_sq_inv, E_sigma_site_sq_inv, V, calculate_credible_interval, credible_interval_width_pct, calculate_savage_dickey, imp_sample_savage_dickey, n_importance_resample) {
    .Call('_BBSS_eval_LC_cross_sectional_covadj_siteadj', PACKAGE = 'BBSS', contrasts, contrast_specification, Y, X, site_indicators, pi_Zqv_eq_h, E_gamma_h_sq_inv, E_mu_h, E_lambda_sq, E_sigma_sq_inv, E_tau_sq_inv, E_sigma_site_sq_inv, V, calculate_credible_interval, credible_interval_width_pct, calculate_savage_dickey, imp_sample_savage_dickey, n_importance_resample)
}

eval_LC_longitudinal_covadj <- function(contrasts, contrast_specification, Y, X, Xrand, pi_Zqv_eq_h, pi_Ztildeqv_eq_h, E_gamma_h_sq_inv, E_mu_h, E_lambda_sq, E_Rqv_h_inv, E_sigma_sq_inv, E_tau_sq_inv, V, calculate_credible_interval, credible_interval_width_pct, calculate_savage_dickey, imp_sample_savage_dickey, n_importance_resampl) {
    .Call('_BBSS_eval_LC_longitudinal_covadj', PACKAGE = 'BBSS', contrasts, contrast_specification, Y, X, Xrand, pi_Zqv_eq_h, pi_Ztildeqv_eq_h, E_gamma_h_sq_inv, E_mu_h, E_lambda_sq, E_Rqv_h_inv, E_sigma_sq_inv, E_tau_sq_inv, V, calculate_credible_interval, credible_interval_width_pct, calculate_savage_dickey, imp_sample_savage_dickey, n_importance_resampl)
}

longitudinal_covadj_siteadj_spatial_map_updates <- function(E_S, E_S_sq, E_Beta, E_Beta_sq, E_b_site, sum_E_b_site_sq, E_Si, trace_E_Si_sq, E_tr_BiBit_qv, Y, X, Xrand, site_indicators, pi_Zqv_eq_h, pi_Ztildeqv_eq_h, E_gamma_h_sq_inv, E_Rqv_h_inv, E_mu_h, Ji, E_lambda_sq, E_sigma_sq_inv, E_tau_sq_inv, E_sigma_site_sq_inv) {
    invisible(.Call('_BBSS_longitudinal_covadj_siteadj_spatial_map_updates', PACKAGE = 'BBSS', E_S, E_S_sq, E_Beta, E_Beta_sq, E_b_site, sum_E_b_site_sq, E_Si, trace_E_Si_sq, E_tr_BiBit_qv, Y, X, Xrand, site_indicators, pi_Zqv_eq_h, pi_Ztildeqv_eq_h, E_gamma_h_sq_inv, E_Rqv_h_inv, E_mu_h, Ji, E_lambda_sq, E_sigma_sq_inv, E_tau_sq_inv, E_sigma_site_sq_inv))
}

longitudinal_covadj_siteadj_spatial_map_updates_fast <- function(E_S, E_S_sq, E_Beta, E_Beta_sq, E_b_site, sum_E_b_site_sq, E_Si, trace_E_Si_sq, E_tr_BiBit_qv, Y, X, Xrand, site_indicators, pi_Zqv_eq_h, pi_Ztildeqv_eq_h, E_gamma_h_sq_inv, E_Rqv_h_inv, E_mu_h, Ji, E_lambda_sq, E_sigma_sq_inv, E_tau_sq_inv, E_sigma_site_sq_inv) {
    invisible(.Call('_BBSS_longitudinal_covadj_siteadj_spatial_map_updates_fast', PACKAGE = 'BBSS', E_S, E_S_sq, E_Beta, E_Beta_sq, E_b_site, sum_E_b_site_sq, E_Si, trace_E_Si_sq, E_tr_BiBit_qv, Y, X, Xrand, site_indicators, pi_Zqv_eq_h, pi_Ztildeqv_eq_h, E_gamma_h_sq_inv, E_Rqv_h_inv, E_mu_h, Ji, E_lambda_sq, E_sigma_sq_inv, E_tau_sq_inv, E_sigma_site_sq_inv))
}

longitudinal_covadj_spatial_map_updates <- function(E_S, E_S_sq, E_Beta, E_Beta_sq, E_Si, trace_E_Si_sq, E_tr_BiBit_qv, Y, X, Xrand, pi_Zqv_eq_h, pi_Ztildeqv_eq_h, E_gamma_h_sq_inv, E_Rqv_h_inv, E_mu_h, Ji, E_lambda_sq, E_sigma_sq_inv, E_tau_sq_inv) {
    invisible(.Call('_BBSS_longitudinal_covadj_spatial_map_updates', PACKAGE = 'BBSS', E_S, E_S_sq, E_Beta, E_Beta_sq, E_Si, trace_E_Si_sq, E_tr_BiBit_qv, Y, X, Xrand, pi_Zqv_eq_h, pi_Ztildeqv_eq_h, E_gamma_h_sq_inv, E_Rqv_h_inv, E_mu_h, Ji, E_lambda_sq, E_sigma_sq_inv, E_tau_sq_inv))
}

update_all_mixing_matrices <- function(A, Y_mixed_QxVN, E_Si, E_sigma_sq_inv) {
    invisible(.Call('_BBSS_update_all_mixing_matrices', PACKAGE = 'BBSS', A, Y_mixed_QxVN, E_Si, E_sigma_sq_inv))
}

apply_unmixing_matrices <- function(Y_unmixed, Y_mixed_QxNV, A) {
    invisible(.Call('_BBSS_apply_unmixing_matrices', PACKAGE = 'BBSS', Y_unmixed, Y_mixed_QxNV, A))
}

rcppeigen_hello_world <- function() {
    .Call('_BBSS_rcppeigen_hello_world', PACKAGE = 'BBSS')
}

rcppeigen_outerproduct <- function(x) {
    .Call('_BBSS_rcppeigen_outerproduct', PACKAGE = 'BBSS', x)
}

rcppeigen_innerproduct <- function(x) {
    .Call('_BBSS_rcppeigen_innerproduct', PACKAGE = 'BBSS', x)
}

rcppeigen_bothproducts <- function(x) {
    .Call('_BBSS_rcppeigen_bothproducts', PACKAGE = 'BBSS', x)
}

